"""
pipeline_configs.py

Configuration for the PreMortem AI multi-stage pipeline.

This module defines adjustable parameters that control how each stage
of the pipeline behaves (discovery → scoring → themes → mitigation → summary).

These settings are intentionally separate from system-wide Settings
so that pipeline behavior can be tuned without altering global defaults.

Used by:
    - the pipeline orchestrator
    - domain-level engines (discovery, scoring, themes, mitigation, summary)
"""

from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class PipelineConfig:
    # -------------------------------------------------------------
    # Discovery Stage
    # -------------------------------------------------------------
    # Maximum number of risks generated by the discovery model.
    max_risks: int = 50

    # Whether to enable latent clustering in the discovery stage.
    # (Future extension — currently unused but wired for compatibility.)
    enable_latent_inference: bool = False

    # -------------------------------------------------------------
    # Scoring Stage
    # -------------------------------------------------------------
    # Whether to allow a specialized reasoning model during scoring.
    enable_reasoning_model: bool = True

    # Number of scoring buckets (1–5 scale by default).
    score_buckets: int = 5

    # -------------------------------------------------------------
    # Theme Clustering Stage
    # -------------------------------------------------------------
    # Minimum number of risks required before themes will be generated.
    min_risks_for_theming: int = 3

    # Maximum themes to generate.
    max_themes: int = 8

    # -------------------------------------------------------------
    # Mitigation Stage
    # -------------------------------------------------------------
    # Maximum mitigations to generate per risk.
    max_mitigations_per_risk: int = 3

    # Enables detailed mitigation explanation blocks.
    include_detailed_explanations: bool = True

    # -------------------------------------------------------------
    # Summary Stage
    # -------------------------------------------------------------
    # Whether the summary stage should run.
    enable_summary: bool = True

    # Maximum number of risks referenced in summary top_risk_ids.
    max_summary_risks: int = 5

    # -------------------------------------------------------------
    # Execution Behavior
    # -------------------------------------------------------------
    # Whether pipeline stages can be skipped dynamically (future support).
    allow_stage_override: bool = False

    # Whether to include metadata/timings in PipelineResponse
    include_pipeline_metadata: bool = True

    # Optional override for the pipeline version (e.g. "v1", "v2-beta")
    pipeline_version: Optional[str] = None


# -------------------------------------------------------------
# Global Singleton – imported everywhere else
# -------------------------------------------------------------

PIPELINE_CONFIG = PipelineConfig()
