// premortem-ai/pipedream/components/final_report/index.js

module.exports = {
  name: "final_report",
  version: "1.0.0",
  description: "Generates the complete structured final report for PreMortem AI.",

  props: {
    risks: {
      type: "object",
      label: "Scored Risks Array",
      description: "The full list of scored risks.",
      required: true,
    },
    themes: {
      type: "object",
      label: "Themes Array",
      description: "High-level themes generated by the themes component.",
      required: true,
    },
    mitigations: {
      type: "object",
      label: "Mitigations Array",
      description: "Mitigation strategies mapped to risks.",
      required: true,
    },
    summary: {
      type: "object",
      label: "Executive Summary",
      description: "Summary object created by the summary component.",
      required: true,
    },
  },

  async run(context) {
    //
    // -------------------------------------
    // INPUT VALIDATION
    // -------------------------------------
    //
    const { risks, themes, mitigations, summary } = context.props;

    if (!Array.isArray(risks) || risks.length === 0) {
      throw new Error("Input 'risks' must be a non-empty array.");
    }

    if (!Array.isArray(themes) || themes.length === 0) {
      throw new Error("Input 'themes' must be a non-empty array.");
    }

    if (!Array.isArray(mitigations) || mitigations.length === 0) {
      throw new Error("Input 'mitigations' must be a non-empty array.");
    }

    if (typeof summary !== "object" || !summary.overview) {
      throw new Error("Input 'summary' must be a valid summary object.");
    }

    //
    // -------------------------------------
    // NORMALIZATION
    // -------------------------------------
    //
    const normalized = {
      risks,
      themes,
      mitigations,
      summary,
    };

    //
    // -------------------------------------
    // PROMPT CONSTRUCTION
    // -------------------------------------
    //
    const prompt = `
You are PreMortem AI. Generate the complete final report as a structured JSON object.

The final report MUST contain:

"executive_summary":
  - overview
  - key_themes
  - top_risks
  - recommended_focus

"risk_overview":
  - total_risks
  - average_severity
  - severity_distribution (low, medium, high)
  - highest_risk (id, title, severity_score)

"themes": full theme objects
"mitigations": full mitigation objects
"top_risks": top 3–5 highest-severity risks

"metadata":
  - generated_at (ISO timestamp)
  - version: "1.0"

Rules:
- Do NOT invent data.
- All references MUST match input IDs.
- Return ONLY valid JSON.

Input Data:
${JSON.stringify(normalized, null, 2)}
`;

    //
    // -------------------------------------
    // LLM EXECUTION (GPT-4.1)
    // -------------------------------------
    //
    const response = await context.$ai.run("gpt-4.1", {
      messages: [
        { role: "system", content: "You are an AI report generator for risk analysis." },
        { role: "user", content: prompt },
      ],
      response_format: {
        type: "json_schema",
        schema: {
          type: "object",
          properties: {
            final_report: {
              type: "object",
              properties: {
                executive_summary: {
                  type: "object",
                  properties: {
                    overview: { type: "string" },
                    key_themes: {
                      type: "array",
                      items: { type: "string" },
                    },
                    top_risks: {
                      type: "array",
                      items: {
                        type: "object",
                        properties: {
                          id: { type: "string" },
                          title: { type: "string" },
                          severity_score: { type: "number" },
                        },
                        required: ["id", "title", "severity_score"],
                      },
                    },
                    recommended_focus: { type: "string" },
                  },
                  required: ["overview", "key_themes", "top_risks", "recommended_focus"],
                },

                risk_overview: {
                  type: "object",
                  properties: {
                    total_risks: { type: "number" },
                    average_severity: { type: "number" },
                    severity_distribution: {
                      type: "object",
                      properties: {
                        low: { type: "number" },
                        medium: { type: "number" },
                        high: { type: "number" },
                      },
                      required: ["low", "medium", "high"],
                    },
                    highest_risk: {
                      type: "object",
                      properties: {
                        id: { type: "string" },
                        title: { type: "string" },
                        severity_score: { type: "number" },
                      },
                      required: ["id", "title", "severity_score"],
                    },
                  },
                  required: [
                    "total_risks",
                    "average_severity",
                    "severity_distribution",
                    "highest_risk",
                  ],
                },

                themes: {
                  type: "array",
                  items: { type: "object" },
                },

                mitigations: {
                  type: "array",
                  items: { type: "object" },
                },

                top_risks: {
                  type: "array",
                  items: { type: "object" },
                },

                metadata: {
                  type: "object",
                  properties: {
                    generated_at: { type: "string" },
                    version: { type: "string" },
                  },
                  required: ["generated_at", "version"],
                },
              },
              required: [
                "executive_summary",
                "risk_overview",
                "themes",
                "mitigations",
                "top_risks",
                "metadata",
              ],
            },
          },
          required: ["final_report"],
        },
      },
    });

    //
    // -------------------------------------
    // RETURN OUTPUT
    // -------------------------------------
    //
    return {
      final_report: response.final_report,
    };
  },
};
